env:
  global:
    - secure: dm8kOqmMkaOqax5DBEyz5EXj4rcuO1OXZ6F8cfR4qz6wV+SPvwzCrPCYTbdoJ8T4eyXG7NG7myFdJ+w60rm4tQQABaM+mrU9RvBiKvWBEUwnmo8PQuIDO/WL6g/ET3mdw1C0YOOfYYEKg/fJlLfDLRJpMrMt8AyVASnTXA9TOLBfyNovkCkkeaGjHqUx4gMDBgwAT7M+PsNfluamtrkUy1BSaECTkVyv3uh1b81lPz3Sa1zcIeqG24FPT7G7Aa3TMQUPCpKd2Pb0+L43Z07EI++P27tRnqwbCBJxVVVcr4DsWCrCUVPNrU4sx4M9mjB72/ci0nq9G0gcklE27+HbVsWx7BrAUSodh/ZMOa6E/aAfpdlVt7K09RBiXx6qS+l48sLYGaepUcoFTukM45IMkgjzJ8zc+zSi5A+F3H3p/Xjii1ZqB0EGLCwoJF+FjAftMExc7DYZxWWJonxm466QIUvT+DPmEH7Hpqnr1oxe8V2lAMh/Fa8FLK9zeqRhe1k+F8Oc5LxueegxKlwCJcaVMb7e2+jMDa6QJwBv5x5Of0zOkxLWPwRuBgbyO1FHGPl8o3qO4eOc7Do9edBimsPA+obHhmMToT23jT2h5Zkx5RPoqSFQkPqCNqhnnNixcpXh7ueZXSogQ1gRALUBrAnEOv/miD1afpr1LX+rYT6ZxcM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
