env:
  global:
    - secure: JYZFacAdsVIUL4EZlyEiE7EtRccaRTuOxEuC6iOoDScsbqixmOO1IHFLRQyUQKse9umEyGvTCZg4oq3OIDOnb5kS99ywcLiCCfnOa/9WAKaB57QHyxXpfITB5hgclvIUzazO9TCAvvl/olfQK/VsKez2B1ELljumLkkOtu60avoxdbAgQgUq8byAvsIe06YBY2bYV9a3rRmZ1XbNOdzLqz2TKa9zTlHGKVJdiFRzkUjyCGF6iCdz0vEFOxhWTBUMtCUxtiZOspc+eB4kYygUbJSgFqKjcOxjlC/pYElR/rDUWT+st0iMJC7DfNkF11bfDiaotqsbUQ1+tM4n9U+Z8dvXDPgWu7MPl3aeNJKD3hr2Di5i3tO62usd4eW0APvlBA+uMLhw40BQdvQy0OK5tVnGqFBi83fg9yvchFsPuOMzDEbc5q29rwpvLbGXin6QwUcD48bzomkHfVwLxfycKTxQQ/InDTJi5vjBZKSZVq2suiwi9W5Nd1gjn+8uZ8G/tkCFc0M8Rb3jdP2xlOP3ok/iGuDUp2gJ3bxjEU/ZIn2Jzk/ByawixAZTfMgUQysPdHrbNhjWIHqtmmZ0Nf8GOUh3rTED0YASdpeOm3QxPOL9cA2AME2VIOCONrsKRdjIjJlxLZTSfxCUvby61l4oDNiM0jRwWC4B5DqyeXnvfiM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
