env:
  global:
    - secure: FZ6/34EKcQKfleO4nLomNDgBCEmeIHuEHooL+4qrNZ66ujb8k2GUfi+68+ZC2AzLuDdThJ+ONMLWTwkoL3DQ7xthUXIiRgqSM1036h2V7WqRrJGMxU2nJQhfwF26+oD9WMTIk/n6DiJbjPAg+sB+6WsDFT/CKYDAU+NWbEWS4hOhU9WljS6R0gWxMzV8mqu+i26rtb84IeK5ZlMgfFtFr/EiqNNImBI73E+RI8bjAhJTX6Z/QqSjE9cicnN+QSINdo6oquVKU1Ixv0qJlrslCVwmPe+efoflU0UaIpvwYilnMgPSFOZpXOohVhs1hGjXEi2hhO9hTIHrECK8tO29EvLxLh/lsQ83mbBLbAKpaGiFOLWWXuSa5Aa0oIlQqFtRwA1k1nVPfw2YL72QL1oZ1V5sy5FEWcKr47kZLHuPCudmWC0/paf5qgjLZFgxtZAup8WuhvamwUfy+QiCQl9N3oFqavK64uhNJI0dk3recE5WmVnEQhvoJiIqnKBO+9Tx8LB/0Xfo4Jjmq6O4wrFTIiil6qIa2EDuagqMzrQnRiXqaqYnj2SVRr4sbS2eeB1Xlg3p1c3ApcJy/LKaT5fkKqlbasSYvXBeP/8ZxeeZbDZPmMSsrN5z2s+EWFIO2E5zBgIqFKXpaRi5MxtRHxEd9+tga2CdeSHHLz3wGDTUX0w=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
