env:
  global:
    - secure: gBG5JAGY/7TaNzRj1PVwWQRTHuddqLWcA1wS/o37W22203O22QfaKK5RXm7u0dmbVO6MAgoVodSARa29nb9KtfrhmVaWC369aAYIwab8GfiVS82dW3O0onTRaU9vihpZWI1INlW1Hdu7EGf2X4kFuOGnJhNxmLuGi/FzKcw1PtocPokoaeiNanGKdm3wpOlfSfQAUpb6TBcjni630xhRDqrRPtt4jMRByEQ9hdo6QZjZcobayuAzMtw8T11qsSFGxrCEp+UZAMNlK+wUGaz/wenS4iWFQL4HgHV7zlw1JlGknvHUZl4g1/AidMs0VCR9+2mo3xjhi4dL+BUPcAeyG955bicvXchcgsByzwe3IpsnUbopqBSREhb9CAOmZfxICP9F09zr/SpIFcv18xmSDGWc1JNLXuTVs+iTIthWUJ/k6OnGjy4ZdFYoRa2numyKbEW4bPZn9G3R24WTQMTrAhj0RxcLCeO/7P0aBFoo0V+lmYLJ5B6lX5hAlB+EbL60jHA2Z163E5KDE/+nxhKDyzrQTbXqzLnA/UGjtdZ+xUz8VlIgoES8GchjgT2X8fLxzTd9AkgITzLkDM/dL2wHsABiJqvIL4OwA2JPRF+LBR6bKpbavWjSOMoKAsQEOl2/N1PiYtb3aprtSOwatp21qg8+/5LKSy9pQYPDa83C1To=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
