env:
  global:
    - secure: C5BBbbnRg3ywnB1gatLqybl+GxO8lmv723i+nFzI4YLLOV9yIQgI5lTXe1C0vqJU6gE90Wc86OWWa5FWFUt37HK7LvQIKZyQl4ZxdLrkgDrSWfhXqtv9uFsXm74JDmEo2Px/Sf30Lg0YkDqdjC0g8iKDWRbjFtM5b1SQ68ZGFjJ0BDGydEYyd2oyhsZuIgtdFhckTI48cQjb95XMUo34GgBvTvHX70Zu3PJFiqkYFREgFHg6vj5BCAVXHGg4orcnMUq9E7RVkJSdA/V0MQQSyf4zcxjNyR5Ry9A/eSOQx7hTlQ28S6LqNjqxf1YnlrZEjiJddahqP/yh7Ps4a4gt5h2ZnTeVrf6boBTZZNnRioR29A9C1vN71orC/YOZ3sZ7zHW/cHw4/L04Hr5Y+LAVx9R5TvlwkawtEoLs/tRfg99Z9hZbTKt+N/qH5QfZIZ19IjeK9GuDp1+t0fMeATFKFnQSP7Ehht2SPJT+XV/1PqtQn5Xb0QPS/ecE9jpjTS1yeTd2le1cWURkZqs6WXGdQudd8bCjXZYcYdFwkgRAVT+dNYbEecBslqaGBRce6Z05X/mNNG1Fu2Vjqv67UDwqGs2sM3TYR6SaXxne+FdB8RIza0Lx92J5tLpl6SRncw67G59bRsEYO/CSVvvnWEWNJ78FCWwaomEZiLahI9WfwGw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
