env:
  global:
    - secure: eofJr6PD3iqVi3CAUrccx+VtsltcfVikzHvi9x9Mz3tZP/JBhH//NtwtwsLlhUdkWMR99xm3/6NUgh70nxQTCkWeRg/2fAWiwbp3ur8nGruCWt3hvTshT/JJHzp+zTCJqD9f4xPYECNQu3JTlofFALNJf+hQQBifwaq7OQtd9BYu4JV2TdmUElwpG2IOhm1CgyivUPi0a2GHpQQ4Eb7BFEuY1nG4LcNIJVpBb00mFkm0ICClaDwXi87sqUs0qRiqPmtbKx0yN3NddA5CW1hf32Z6nqISjAxNR9lP4xDyPygBqjhMcEZz3WS5OrDGvkaeWEEWYF6RBzuKEQqkt4Q1HDtQykSKAaixi4j8y8axakuXMOt0tml6sEkd1eJjv0wyi3lH95bFzFoYzesPbPLRpj3lGZ28WLl+q+2v5tWPH/oV6K6nrH6ufcASY63wrlUxR0+sw9oSAg81o4VJJQw9rdyHIUyBn6lc8xvnU9m2R+74/6+UWUOFJycYLzPtBkM0m9goY7GGDLsXBZ6NSqRiMHZobzvp/cfRTaVU6i2JCs13VejbTV7cOOtG3s6VJMpGtG659aUlTwqiqnpcbV1LPKLQtnf4DBEyMiYRptQ/A6Om0fEr8zNsvDsJTY4ghuT2BCz9CeBZnFn/Ovgf/x9Z4LP3To1+XRlGkWlD+AZnyYI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
