env:
  global:
    - secure: Ycg/DvscFrj/YrnhTetDdrW+vhA5/KL523JikKX9IDuv+opf50/jHfa48feBOZGMWvwKLzzlTrGyU7sZzUagBg36cvZ77BBhvi15R59llD4fxPORSrK7g8ElIDwr1lSJ/uarO76Uz8UUvzHEGWAzcs8hFWcBqFWU5UKrj7ud8jPmiokMKZDVunVH2Z4swsaCkZeQFpEhTJmjW7/JEmIcI1yNTXHhLO8S5/681qR7NdXluD+aMvITVxWIC/2rueloaGd6w6oWBuz06YRpvpbnIe1dMuZFURvpNZdqOYnkaLH/cVxcqtZAvuFeAUEqXTKTRJMnyJGPECPvOdaGITkqJAOHuyj7+2uwrMPyyFJW0RAq+TYMUpxCUTz5JbaGTXFGWCfT6rlueo754cDzIJzqd6B23OJLMpV3yGLWUNnka/atUkvgRjqqbu6LxiU6OAUXkkQsfj84IZbvfUeo2qH5rSCJz7CQXW0IFo8T9dBXrXX8tRgRY27cqY7gWM21OeE/TatM8zo3lxdTSUderIQMNEBS/PvtVLkh60g1H/DKgI1pQjyT6cNI3xD3ad4ElZppu/nzYovmijcijhasS9bgYCfPiQVLmzKbZUFqTtKjdfDhwmmI82vbCaA++c6Gc1dEvcf3mgcLKMxzS9PM3fVpSQAXP6q1xMWvP/uOX/eHdYQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
