env:
  global:
    - secure: OlCt31CfRo2LqPGXgNCAb37X3swQ57K+xmK9W0PTbBEoedFhWFgrzZTOry7BAM5RDsS2xbc20Gzvg4Wkiw7NX52HHgKGtGh0hc8/As1qCCIzH+Sr/ExMKsxSm7iuHCxPMFkJOU2XEPMvACmku+8cPEb2ynwOYYerhRkLZgVH+kGLBGMhoLmd3zGFlA75EtE2uknI0QzVc+bEYk85ipEICqPiIX2s9pxVgVBMEIzzIghf/YKmUqbP7e+XricT0A+RALxTElNlWlyYhW3ErhlUdUrup/Hnqj5Wo4Nkr/41LuAdkF7u1f1HRDNxt2lZ4hEd3mfb8Q105D4rhADW6Aedca8M49AgRHWwRJudQAfYCV+Fo6aXy6YxecBdhYWMXDV1BqRe0K5FefggUYFR3E5EsbXlWguAn03wESm/oqd6RQVSmJXJN352R+Y9PIN7NTR+FA6iflh2SB+T45WAOBcTTp0z9UZ2/7ZfTXp0VH+Bn1ZC+rvnu/y2X3c+1gcR1de2pJ/LRcnFxJ1bblODd8e6scja0NohXFS8BX3G+62iH8kbAoqFo7BwGJIk3IaAIjaQnLDFrKe5Q/zcPZlpU4rJh66zpgOlSZhsogc+Dt8NFPvq+XsNMBh/imHYjLooA9NlwyIev/Eg9QGlBXpnOqhFUUeXWcfvxMbCbZw6+Gg0tlc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
