env:
  global:
    - secure: HkD8vfnU4BCvCbeGLnnA8DmHkAEJW8TOkZYY9WgEUTu5dokBr6BPAN5tvOShxaxug7e1mD9Bc1weJq/DfLqorv2HjSP8ptraJGg598YucgoYsngPU5BTYUv/N1HbV3xDihGApEL+i2sdJcvTLBEJ6wNoWu+J5yivDtaT8bUBSMEjn5yZDpy/04NA7rMmR/0lyG1V17T4FbS7DBBpu3T+J1ciKn/InWmziJDMZkc0IWsb2hnZm3HjJ7vdSBFQlw4W4NDD/E3/jJLeRo2telXsHnytdIFYoaABriMj/gIxfK1gEBp/9uTs58e4vqvHUax+KeZHBv0bHCZ81Ssk+Fh1WGjNZpkLGSednPyDUTpjqshrGIx5o3p1tYsG6e54NuMfaODCfJdHP1yJhd0RBw0QkDfjKyUahHgA4fTKbND2bvXR0uk4JMdnYvzv4P0g1OOOelvVwcOh/3Qp29TiiiEKLRrMzpNxerJyOlQ3ZU6l7t1DBs/VMdLR4kdROVpsOotXngnsgoe9ubQJ6XcMbZyU+crammrH2rVnNXue/14ZbTUAYRZ2iUi4Pg4zzib/zPJBivEaK6hm1o1CEU7/LfCyqN/zczLHL3tX1JrKMJhsqIN9FCuxPzvuvwioiIusH9uJ8f6rJMiFua9BbxnbMKlwE3nGUi9VvUNrYj3rfgjQK9I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
