env:
  global:
    - secure: ilGE8x/X7Tx0nfirnY2IFCJPRQnmBnxn/sHCBxobqcsDGkPsOBXf8kR5AbgPyIZEwJDZ8b66Gwwwk7+UterFg5SkVX0p3GqR7W99WfMciCNrZWId7huaTAl0RJvQ6cl/knTlstwblJWwYUD+irXIO+nP06CXfrRzwxYVO0oV0jJnKjsDFVbwrUTlK4/9Bumu6S6bqA8DWbGRJcTHma7d3xK/m08H2PRMCmreC5Pqmtrq6AxLYjNL/iPCzUxtPXIb/HzlCANtiVrIcMUK2MzVTNEooMU/g73QPc/1ZNV/qnw9UIj3sPqr9Nd8RJJOdlcsY7cZpOcV0fzSEtQlKgt11RsXrXBAE4H0jfQyNFLKEtceXc3DuCEgOV18rkaarqjC0u/gC/FFzaF1cCGjvfdkrXr5Ceh1lAVa19+2ymrVq/l0PK1is2K6/q+pWDViKa3XyQeRnTLaiaJx1r+RtgI2jZNhmikJp0tE4KhVcpR/zOEX3lOjvUCZDwutD+1ZBiviF+6mKBl8FMyoRJghtaioPnDXWvJB/EIWAJIgZZ4dTkotG2X530r1hrhttnVwP6Tw4rq5sORIrNDYKZii3bMOxZ8xdJiEWYqjA6O/FYtZl3bQ78rlW14Sn+XtkZvQ54Yu3bp9pSMl/7Ro2U2sXtDz2EnfCGk2aPBHjX2mCGAPFAs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-spy_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
